### ISSUE TITLE
Dédoublement de passagers

### ISSUE THREAD

**Issue by WilliamHdd** [azerupi/PHP-reservation-app#14]
Pour le moment si on modifie ou recharge la page, les passagers sont recréés en double dans la base de donnée. A résoudre

**Comment by WilliamHdd** [comment]
Le soucis est quand lors du chargement des passagers d'un voyage on créé X objet passagers, mais qu'entre l'étape 2 (où on donne les infos des passagers) et le récap on les recréé (step 2 dans app.php). 

Du coup chaque passager existant est dupliqué. Il faudrait faire en sorte que à l'étape avant le récap il vérifie si il a déjà un passager similaire ou non . Ou alors effacer le passager dans la BdD une fois importé... Qu'elle solution pense tu être la plus simple et plus efficace ?

**Comment by azerupi** [comment]
Je pense que le problème vient du fait qu'on utilise `add_passenger` même quand on modifie ou recharge. Ce qui fait qu'on se retrouve avec les passagers en double. Moi je viderait la liste dans le modèle juste avant de faire les `add_passengers`. C'est pas optimal, mais ça devrait résoudre le problème.

Normalement l'écriture dans la BD ce fait seulement à la fin...? A moins que t'ai pas fait ça comme ça? Dans quel cas le problème ne sera pas résolu. Il faut absolument que l'écriture dans la BD se fasse en une fois à la fin. Par exemple quand on appel une méthode `save()` sur notre modèle `Reservation`

**Comment by WilliamHdd** [comment]
add_passenger ne change que n_passengers :) c est juste le nombre total qui est changé, ça change rien au fait qu'on les créé 2 fois

**Comment by azerupi** [comment]
[Nope, ça rajoute un passager dans `Reservation`](https://github.com/azerupi/PHP-reservation-app/blob/master/models/reservation.php#L66)

Du coup quand tu prends la reservation de la session, elle contient déjà les passagers. Quand tu renvoie le formulaire tu rajoute les passagers une deuxième fois.

**Comment by WilliamHdd** [comment]
problème résolut :) il met a jour comme un grand les voyage et les passagers :D
